AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    MemorySize: 1024
    Architectures:
    - Ref: LambdaArchitecture
    Timeout: 30
    Tracing: Active
    Environment:
      Variables:
        LINK_TABLE_NAME:
          Ref: Table
Parameters:
  LambdaArchitecture:
    Type: String
    AllowedValues:
    - arm64
    - x86_64
    Description: Enter arm64 or x86_64
    Default: x86_64
Resources:
  GetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /list
            Method: POST
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: dynamodb:Scan
          Resource:
            Fn::GetAtt:
            - Table
            - Arn
      ImageUri: getlistfunction:dotnet7aot-v1
    Metadata:
      DockerBuildArgs:
        SAM_BUILD_MODE: run
      DockerContext: C:\Users\User\Documents\SOLUTIONS\shareusefulness\src\LinkService
      DockerTag: dotnet7aot-v1
      Dockerfile: ./ShareUsefulness.Links.Functions/Dockerfile
      SamResourceId: GetListFunction
  AddLinkFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /add
            Method: POST
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource:
            Fn::GetAtt:
            - Table
            - Arn
      ImageUri: getlistfunction:dotnet7aot-v1
    Metadata:
      DockerBuildArgs:
        SAM_BUILD_MODE: run
      DockerContext: C:\Users\User\Documents\SOLUTIONS\shareusefulness\src\LinkService
      DockerTag: dotnet7aot-v1
      Dockerfile: ./ShareUsefulness.Links.Functions/Dockerfile
      SamResourceId: AddLinkFunction
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Link
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
