version = 0.1
[default.deploy.parameters]
stack_name = "anothersamapp"
resolve_s3 = true
s3_prefix = "anothersamapp"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaArchitecture=\"x86_64\""
image_repositories = ["GetListFunction=147407883976.dkr.ecr.us-west-1.amazonaws.com/anothersamapp5a4ea555/getlistfunctionc957eda2repo"]
