using System.Text.Json.Serialization;

namespace ShareLink.Web.Errors;

public class ValidationError(string[] errors)
{
    public string Type => "validation_error";

    /// <summary>
    /// The HTTP status code([RFC7231], Section 6) generated by the origin server for this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-3)]
    public int? Status => StatusCodes.Status400BadRequest;

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    [JsonPropertyOrder(-1)]
    public string[] Errors { get; } = errors;
}