name: Build and Deploy to Azure

on:
  push:
    branches:
      - main
#    paths:
#      - 'server/**'

jobs:
  deploy-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore ./server/src/ShareLink.Web/ShareLink.Web.csproj

      - name: Build
        run: dotnet build ./server/src/ShareLink.Web/ShareLink.Web.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./server/src/ShareLink.Web/ShareLink.Web.csproj --configuration Release --no-build --output ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ShareLinkApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_31B5AB9BCEE84C828AFB648146FAFC2F }}
          package: ./publish